tasks:
  - repository: /var/restic/database
    password: "2dkNKCVT9AgFaV8g"
    path: /var/databases
    retention: 31d
    prespawn: hooks/db_pre.sh
    postspawn: hooks/db_post.sh
  - repository: /var/restic/acl
    password: "bEQokh6iQm9rwmfz"
    path: /var/acls
    retention: 2y5m7d3h
    prespawn: hooks/acl_pre.sh
    postspawn: hooks/acl_post.sh
  - repository: /var/restic/log
    password: "gjUMKMDcVHwN9Jah"
    path: /var/log
    retention: 2m15d
    regexes:
      - "*.gz"
